// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class CategoriasCliente
{
    public int CategoriaID { get; set; }

    public string NombreCategoria { get; set; }

    public string Descripcion { get; set; }

    public decimal? DescuentoAplicable { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();
}