// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class CategoriasProducto
{
    public int CategoriaProductoID { get; set; }

    public string NombreCategoria { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}