// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class Clientes
{
    public int ClienteID { get; set; }

    public string NombreCliente { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Direccion { get; set; }

    public int CategoriaID { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public bool? Activo { get; set; }

    public virtual CategoriasCliente Categoria { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();
}