// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class Pedidos
{
    public int PedidoID { get; set; }

    public int ClienteID { get; set; }

    public int UsuarioVendedorID { get; set; }

    public DateTime? FechaPedido { get; set; }

    public string EstadoPedido { get; set; }

    public decimal? Total { get; set; }

    public int? RutaID { get; set; }

    public DateTime? FechaEntregaProgramada { get; set; }

    public string Observaciones { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<DetallePedidos> DetallePedidos { get; set; } = new List<DetallePedidos>();

    public virtual RutasEntrega Ruta { get; set; }

    public virtual Usuarios UsuarioVendedor { get; set; }
}