// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class Productos
{
    public int ProductoID { get; set; }

    public string NombreProducto { get; set; }

    public int CategoriaProductoID { get; set; }

    public decimal PrecioUnitario { get; set; }

    public int? Stock { get; set; }

    public int? StockMinimo { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual CategoriasProducto CategoriaProducto { get; set; }

    public virtual ICollection<DetallePedidos> DetallePedidos { get; set; } = new List<DetallePedidos>();
}