// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class PuntosVenta
{
    public int PuntoVentaID { get; set; }

    public string NombrePunto { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public TimeOnly? HorarioApertura { get; set; }

    public TimeOnly? HorarioCierre { get; set; }

    public int ZonaID { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual ZonasGeograficas Zona { get; set; }
}