// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class Repartidores
{
    public int RepartidorID { get; set; }

    public string NombreCompleto { get; set; }

    public string Cedula { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string LicenciaConducir { get; set; }

    public string VehiculoAsignado { get; set; }

    public int? ZonaAsignada { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaIngreso { get; set; }

    public virtual ICollection<RutasEntrega> RutasEntrega { get; set; } = new List<RutasEntrega>();

    public virtual ZonasGeograficas ZonaAsignadaNavigation { get; set; }
}