// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class RutasEntrega
{
    public int RutaID { get; set; }

    public string NombreRuta { get; set; }

    public int ZonaID { get; set; }

    public int? RepartidorAsignado { get; set; }

    public decimal? CapacidadMaxima { get; set; }

    public int? TiempoEstimado { get; set; }

    public bool? Activa { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();

    public virtual Repartidores RepartidorAsignadoNavigation { get; set; }

    public virtual ZonasGeograficas Zona { get; set; }
}