// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int UsuarioID { get; set; }

    public string NombreUsuario { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int RolID { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();

    public virtual Roles Rol { get; set; }
}