// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacilSD.Infraestructura.AccesoDatos;

public partial class ZonasGeograficas
{
    public int ZonaID { get; set; }

    public string NombreZona { get; set; }

    public string Descripcion { get; set; }

    public bool? Activa { get; set; }

    public virtual ICollection<PuntosVenta> PuntosVenta { get; set; } = new List<PuntosVenta>();

    public virtual ICollection<Repartidores> Repartidores { get; set; } = new List<Repartidores>();

    public virtual ICollection<RutasEntrega> RutasEntrega { get; set; } = new List<RutasEntrega>();
}